# Generated by Django 3.0.3 on 2020-02-28 23:54
'''
url = base_novel_url.format(novel_id)
    html = lr.get(url)
    if html:
        soup = BeautifulSoup(html, 'lxml')
        title = soup.find('div', id='info').h1.string.strip()
        img = soup.find('div', id='fmimg').img['src'].strip()
        author_string = soup.find('div', id='info').p.string
        state_string = ''.join(soup.find('div', id='info').p.next_sibling.next_sibling.strings)
        finished = '连载中' not in state_string
        author = re.match(r'.+：(.+)', author_string).group(1).strip()
        intro = soup.find('div', id='intro').string.strip()
        category = soup.find('meta', property='og:novel:category')['content']

        db = mysql_manager.get_db()
        cursor = db.cursor()
        sql = "select * from category where name='{0}'".format(category)
        try:
            cursor.execute(sql)
            result = cursor.fetchone()
            category_id = result[0]
            insert_sql = "insert into novel (title, intro, author, category_id, finished, img) " \
                  "values ('{0}', '{1}', '{2}', '{3}', {4}, {5})".format(
                title, intro, author, category_id, int(finished), img)
            cursor.execute(insert_sql)
            db.commit()
            print("插入小说数据成功")
            novel_id = cursor.lastrowid
            chapters = soup.find_all('dd')
            for chapter in chapters:
                chapter_url = domain_url + chapter.a['href']
                crawling_chapter.crawling(chapter_url, novel_id)
        except Exception as e:
            print("插入小说操作出错", e)
            db.rollback()
        db.close()
'''

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novel',
            new_name='Book',
        ),
    ]
